apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Flask environment — overridden per overlay
  APP_SETTINGS: "config.ProductionConfig"
  # Internal service URLs — use k8s DNS service names
  AI_SERVICE_URL: "http://ai-service:8001"
  SES_SENDER_EMAIL: "jeffreyvole@gmail.com"
  BASE_URL: "http://k8s-explaina-explaina-0ed1c0e65f-1292707217.us-west-1.elb.amazonaws.com"
