apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: explainalgo-prod

bases:
  - ../../base

resources:
  - patches/hpa.yaml
  - postgres-sealed-secret-prod.yaml
  - app-sealed-secret-prod.yaml

patches:
  - path: patches/resources-api-gateway.yaml
    target:
      kind: Deployment
      name: api-gateway
  - path: patches/resources-frontend.yaml
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: replace
        path: /data/BASE_URL
        value: http://k8s-explaina-explaina-3bee6f1bcb-1372552135.us-west-1.elb.amazonaws.com
    target:
      kind: ConfigMap
      name: app-config
