"""Updated Problems Table. Added example column and changed rubric column to allow nullables.

Revision ID: 9235e6f52da4
Revises: d3985c5244e7
Create Date: 2024-12-20 23:02:14.547276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9235e6f52da4'
down_revision = 'd3985c5244e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('example')

    # ### end Alembic commands ###
