"""Updated Problems Table. Added description, example, rubric columns.

Revision ID: d3985c5244e7
Revises: 7fc4e343a31f
Create Date: 2024-12-19 22:19:26.241972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3985c5244e7'
down_revision = '7fc4e343a31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('rubric')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
