"""Renaming Table ProblemList to Problem

Revision ID: e9e3b6ef3e78
Revises: f9212c7bd6f2
Create Date: 2024-08-16 02:00:49.494502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e3b6ef3e78'
down_revision = 'f9212c7bd6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('problem_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('difficulty_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], name='problem_list_difficulty_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='problem_list_pkey')
    )
    op.drop_table('problem')
    # ### end Alembic commands ###
