"""Added ProblemList and Difficulty Models

Revision ID: f9212c7bd6f2
Revises: 
Create Date: 2024-08-12 16:59:49.878186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9212c7bd6f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('problem_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_list')
    op.drop_table('difficulty')
    # ### end Alembic commands ###
